name: NIFTY 50 Daily Report

on:
  schedule:
    - cron: '30 2 * * *'  # Every day at 8:00 AM IST (2:30 AM UTC)
  workflow_dispatch:      # Optional: allows manual trigger from GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests nsepython

      - name: Run script
        run: python script.py
